## ┌───────────────────────────────────────────────────────────────────────────┐
## │                                MAKEFILE                                   │
## └───────────────────────────────────────────────────────────────────────────┘



NAME	     ?=	libprotocol.a


SRCS =	      	ARequest.cpp		\
		ServerRequest.cpp	\
		FriendRequest.cpp	\
		Protocol.cpp		\
		RequestFactory.cpp	\

API.H=		./API/

F.C	     +=	-W -Wall 
F.I	     += -I$(API.H)
F.D	     +=


all:		start $(NAME)

$(NAME):	lib_compile

clean:		remove_objects

fclean:		clean remove_name

re:		fclean all























































include .libmake
