## ┌───────────────────────────────────────────────────────────────────────────┐
## │                                MAKEFILE                                   │
## └───────────────────────────────────────────────────────────────────────────┘



NAME	     ?=	libMDynamic.a

SRCS =		DynamicAbstract.cpp


F.C	     +=	-W -Wall
F.I	     +=	-I$(DIR.H)
F.L	     +=
F.D	     +=


all:		start $(NAME)

$(NAME):	lib_compile

clean:		remove_objects

fclean:		clean remove_name

re:		fclean all























































include .libmake
