CALL.DIR=	./call
AUTH.DIR=	./auth
CHAT.DIR=	./chat
FRIEND.DIR=	./friends
PERSO.DIR=	./perso

install:
	@make --no-print-directory -C $(CALL.DIR) install
	@make --no-print-directory -C $(AUTH.DIR) install
	@make --no-print-directory -C $(CHAT.DIR) install
	@make --no-print-directory -C $(FRIEND.DIR) install
	@make --no-print-directory -C $(PERSO.DIR) install
